version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "composer"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "php"
    allow:
      - dependency-type: "all"